name: bandicoot_orm
version: 0.0.1
description: An entity and query building tool.
repository: https://github.com/santiagoramirez/bandicoot/tree/master/packages/bandicoot_orm
environment:
  sdk: '>=2.12.0 <3.0.0'
