name: bandicoot
version: 1.0.0
description: Suite of tools for developing on the frontend and the backend.
repository: https://github.com/santiagoramirez/bandicoot
environment:
  sdk: '>=2.12.0 <3.0.0'
